# ==========================
# Application Settings
# ==========================
spring.application.name=screenshot-monitor-agent
server.port=9090
spring.main.headless=false

# ==========================
# Screenshot Agent Settings
# ==========================
screenshot.interval.minutes=30
screenshot.storage.path=./screenshots
agent.id=agent-001

# ==========================
# Backend API Settings
# ==========================
backend.api.screenshot-upload-url=http://localhost:9090/api/screenshots/upload

# ==========================
# Database Settings (MySQL)
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/DesktopMonitoringDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / Hibernate Settings
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ==========================
# Cloudinary Settings
# ==========================
cloudinary.cloud_name=dnpmn8agl
cloudinary.api_key=787535992935861
cloudinary.api_secret=EsU9VnFtC-VBRyNB4RuE-OxLuqc

# ==========================
# ==========================
# JWT Settings
# ==========================
jwt.secret=thisIsASuperStrongSecretKeyChangeMe1234567890

# Expiration time in milliseconds (3600000 = 1 hour)
jwt.expiration=3600000



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=v.rathore@braininventory.com
spring.mail.password=jqylchrblsrnlkpw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG



backend.activity.url=http://localhost:9090