# ==========================
# Backend API Settings
# ==========================
backend.api.screenshot-upload-url=http://localhost:9090/api/screenshots/upload
backend.activity.url=http://localhost:9090/api/monitor/activity
backend.api.key=${BACKEND_API_KEY}

# ==========================
# Database Settings
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ==========================
# Cloudinary Settings
# ==========================
cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${CLOUD_API_SECRET}

# ==========================
# JWT Settings
# = :--- | :--- | :---
jwt.secret=${JWT_SECRET}

# ==========================
# Mail Settings
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG

# ==========================
# Application URLs
# ==========================
app.base-url=http://localhost:9090
app.reset-password.path=/api/auth/reset-password?token=


# ==========================
# Web tracking agent
# backend.api.key=your-api-key
backend.website.url=http://localhost:9090/api/website-usage

# 5 seconds
agent.website.interval=5000